# 
# GitHub Actions workflow.
#
# Reusable cdBuild
#

name: Reusable cdBuild

on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string
jobs:

  reusable-cdBuild:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    env:
      VERSION: ${{ github.sha }}
      USER: ${{ secrets.USER }}
      PAT: ${{ secrets.PAT }}

    steps:
      
      # Check-out repo under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3

      # cdBuild
      - name: cdBuild
        run: ./${{ inputs.module }}/cd-scripts/cdBuild.sh
