# 
# GitHub Actions workflow.
#
# Reusable cdBuild
#

name: Reusable cdBuild

on:
  workflow_call:
    inputs:
      module:
        required: false
        type: string
jobs:

  cdBuild:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Check-out repo under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3
        name: Checkout

      # cdBuild via input
      - name: cdBuild with input module
        if: "${{ inputs.module != '' }}"
        run: ./${{ inputs.module }}/cd-scripts/cdBuild.sh

      # cdBuild via workflow
      - name: cdBuild with github.workflow module
        if: "${{ inputs.module == '' && github.workflow != '' }}"
        run: ./${{ github.workflow }}/cd-scripts/cdBuild.sh

      # Dump contexts
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      # Status
      - name: Success
        if: ${{ success() }}
        run: echo "### Success! :star:" >> $GITHUB_STEP_SUMMARY

      # Status
      - name: Error
        if: ${{ !success() }}
        run: echo "### Error! :boom:" >> $GITHUB_STEP_SUMMARY
