# 
# GitHub Actions workflow.
#
# Reusable cdBuild
#

name: Reusable cdBuild

on:
  workflow_call:
    inputs:
      module:
        required: false
        type: string
jobs:

  cdBuild:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Check-out repo under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3
        name: Checkout

      # cdBuild via input
      - name: cdBuild with input module
        if: "${{ inputs.module != '' }}"
        run: ./${{ inputs.module }}/cd-scripts/cdBuild.sh

      # cdBuild via workflow
      - name: cdBuild with github.workflow module
        if: "${{ inputs.module == '' && github.workflow != '' }}"
        run: ./${{ github.workflow }}/cd-scripts/cdBuild.sh
