# 
# GitHub Actions workflow.
#
# Reusable cdRelease
#

name: Reusable cdRelease

on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string
jobs:

  cdRelease:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    env:
      VERSION: ${{ github.sha }}
      USER: ${{ secrets.USER }}
      PAT: ${{ secrets.PAT }}

    steps:
      
      # Check-out repo under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3

      - run: |
          echo "${{ env.KEY }}"
          echo "${{ env.USER }}"
          echo "${{ env.PAT }}"

      # cdRelease
      - name: cdRelease
        run: ./${{ inputs.module }}/cd-scripts/cdRelease.sh
