# 
# GitHub Actions workflow.
#
# Reusable cdRelease
#

name: Reusable cdRelease

on:
  workflow_call:
    inputs:
      module:
        required: false
        type: string
jobs:

  cdRelease:
    if: contains(fromJSON('["main", "master"]'), github.ref_name)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Check-out repo under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3

      # Show github context
      - name: Show github context
        run: echo ${{ toJSON(github) }}

      # cdRelease via input
      - name: cdRelease with input module
        if: "${{ inputs.module != '' }}"
        run: ./${{ inputs.module }}/cd-scripts/cdRelease.sh

      # cdRelease via workflow
      - name: cdRelease with github.workflow module
        if: "${{ inputs.module == '' && github.workflow != '' }}"
        run: ./${{ github.workflow }}/cd-scripts/cdRelease.sh

      # Status
      - name: Success
        if: success()
        run: echo "### Success! :star:" >> $GITHUB_STEP_SUMMARY

      # Status
      - name: Error
        if: !success()
        run: echo "### Error! :boom:" >> $GITHUB_STEP_SUMMARY
