# 
# GitHub Actions workflow.
#
# Reusable cdRelease
#

name: cdRelease

on:
  workflow_call:
    inputs:
      module: { type: string, required: false }

jobs:
  cdRelease:
    if: contains(fromJSON('["main", "master"]'), github.ref_name)
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Check-out repo under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3

      # cdRelease via input
      - name: cdRelease with input module
        if: "${{ inputs.module != '' }}"
        run: ./${{ inputs.module }}/cd-scripts/cdRelease.sh

      # cdRelease via workflow
      - name: cdRelease with github.workflow module
        if: "${{ inputs.module == '' && github.workflow != '' }}"
        run: ./${{ github.workflow }}/cd-scripts/cdRelease.sh

      # Dump contexts
      - name: Dump GitHub context
        if: ${{ !success() }}
        run: echo "${{ toJson(github) }}"
      - name: Dump runner context
        if: ${{ !success() }}
        run: echo "${{ toJson(runner) }}"
