# 
# GitHub Actions workflow.
#
# m1 cdBuild
#

name: m1 cdBuild

on:
  push:
    branches: 
      - '**'
      - '!main'
    paths:
      - 'm1/**'
      - .github/workflows/m1*
  workflow_dispatch:

jobs:

  cdBuild:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    env:
      VERSION: ${{ github.sha }}
      USER: ${{ secrets.USER }}
      PAT: ${{ secrets.PAT }}

    steps:
      
      # Check-out repo under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3

      # cdBuild
      - name: cdBuild
        run: ./m1/cd-scripts/cdBuild.sh
