# 
# GitHub Actions workflow.
#
# m2 build.-release
#

name: m2 build-release

on:
  push:
    branches: 
      - '**'
    paths:
      - 'm2/**'
      - .github/workflows/m2*
  workflow_dispatch:

jobs:

  Build:
    uses: ./.github/workflows/cdBuild.yaml
    with:
      module: m2

  Release:
    needs: Build
    if: contains(fromJSON('["main", "master"]'), github.ref_name)
    uses: ./.github/workflows/cdRelease.yaml
    with:
      module: m2
